export const en = {
  brand: 'AL', world: 'THE NEON ROOM', edition: 'PORTFOLIO / 2026',
  name: 'Alex Lin', firstName: 'Alex', lastName: 'Lin', role: 'Frontend engineer.',
  roleSecond: 'World builder.', location: 'TAIPEI, TAIWAN', availability: 'Open to opportunities',
  introduction: 'Thoughtful interfaces. Playful experiences. A little neon after dark.',
  enter: 'Explore my work', resume: 'Resume PDF', resumePending: 'Resume coming soon',
  room: 'PERSONAL SPACE', roomNumber: 'ROOM 01', roomStatus: 'AFTER HOURS',
  sections: { profile: 'Profile', skills: 'Skills', interests: 'Interests', experience: 'Experience', projects: 'Projects', contact: 'Contact' },
  furniture: { profile: 'Profile signal', skills: 'Skill console', interests: 'Personal mode', experience: 'Career archive', projects: 'Project playlist' },
  quickAccess: 'Quick access', language: 'Language', soundOn: 'Mute audio', soundOff: 'Enable audio',
  motionOn: 'Reduce motion', motionOff: 'Enable motion', close: 'Close',
  loading: 'Connecting to room...', sceneError: 'Room unavailable. All sections are available below.',
  placeholder: 'DEMO CONTENT', placeholderNote: 'Sample information. Final details are on the way.',
  footer: 'A SMALL ROOM. A WORLD OF POSSIBILITIES.', copyright: '2026 / ALEX LIN',
  panelCode: 'PERSONAL ARCHIVE', next: 'Next section', contactCta: 'Let\'s build something',
  profile: {
    title: 'Behind the screen', subtitle: 'ENGINEER / CREATOR / EXPLORER',
    paragraphs: ['I am a web developer focused on building clear, responsive, and interactive digital experiences.', 'I bring frontend engineering, motion, and product thinking together to turn ideas into interfaces that feel good to use.', 'From everyday web products to small playable worlds, I care about the details that make technology feel human.'],
    tags: ['Frontend Web Engineer', 'H5 Web Game Developer', 'Full-Stack Engineer', 'Senior Engineer'],
  },
  skills: { title: 'Tools of the trade', subtitle: 'DEVELOPMENT SKILLS', intro: 'From the first interaction to the service behind it.', groups: [
    { name: 'Frontend', items: ['React', 'TypeScript', 'Vite', 'Responsive UI'] },
    { name: 'Interactive', items: ['PixiJS', 'Cocos', 'Canvas', 'Game UI'] },
    { name: 'Backend', items: ['Golang', 'Gin', 'REST API', 'Redis', 'PostgreSQL'] },
    { name: 'Workflow & quality', items: ['Git', 'GitHub', 'Performance', 'i18n', 'Accessibility', 'CSP'] },
  ] },
  interests: { title: 'Off the clock', subtitle: 'PERSONAL MODE', intro: 'The things that keep curiosity switched on.', items: [
    { title: 'Pixel worlds', description: 'Small details, big atmosphere. Retro games and pixel art are a constant source of inspiration.' },
    { title: 'Interactive stories', description: 'Exploring how a simple interaction can turn a visitor into part of the story.' },
    { title: 'Creative experiments', description: 'Building little web experiences just to see where an idea might lead.' },
    { title: 'Quiet focus', description: 'A good playlist, a calm workspace, and time to learn something new.' },
  ] },
  experience: { title: 'The journey so far', subtitle: 'CAREER ARCHIVE', jobs: [
    { role: 'Frontend Developer', company: 'Neon Studio', period: '2024 - Present', points: ['Built responsive interfaces for customer-facing web products.', 'Improved interaction quality, performance, and accessibility.', 'Partnered with designers and backend engineers from prototype to release.'] },
    { role: 'Web Developer', company: 'Pixel Lab', period: '2022 - 2024', points: ['Integrated APIs and managed application state.', 'Created reusable components and interactive web experiences.'] },
    { role: 'Junior Developer', company: 'Interface Works', period: '2021 - 2022', points: ['Delivered responsive pages and maintained web applications.'] },
  ] },
  projects: { title: 'Things I have built', subtitle: 'PROJECT PLAYLIST', intro: 'A few selected projects and late-night experiments.', pending: 'Link coming soon', demo: 'Live site', source: 'Source', caseStudy: 'Case study', items: [
    { id: 'neon-dashboard', title: 'Neon Dashboard', type: 'WEB APPLICATION', description: 'An analytics workspace that brings complex information into focus.', stack: ['React', 'TypeScript'], art: 'dashboard' },
    { id: 'pixel-portfolio', title: 'Pixel Portfolio', type: 'INTERACTIVE EXPERIENCE', description: 'A personal corner of the internet, reimagined as a playable room.', stack: ['PixiJS', 'React'], art: 'room' },
    { id: 'api-control-room', title: 'API Control Room', type: 'FULL-STACK PRODUCT', description: 'A connected admin interface for managing services and data.', stack: ['Golang', 'REST API'], art: 'terminal' },
    { id: 'game-ui', title: 'Game UI Prototype', type: 'H5 GAME EXPERIMENT', description: 'Exploring responsive game interfaces and satisfying micro-interactions.', stack: ['Cocos', 'Canvas'], art: 'game' },
  ] },
  contact: { title: 'Open a channel', subtitle: 'LET\'S CONNECT', intro: 'Have an interesting project, a role in mind, or just something to share?', email: 'Email', github: 'GitHub', linkedin: 'LinkedIn', pending: 'Contact details coming soon' },
};
